daily_planner/urls.py
from django.urls import path

from . import views

app_name='daily_planner'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='result'),
    path('<int:goal_id>/vote/', views.vote, name='vote'),
]

my_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('daily_planner/', include('daily_planner.urls')),
    path('admin/', admin.site.urls),
]

daily_planner/models.py
from django.db import models
from django.utils import timezone
import datetime


class Goal(models.Model):
    goal_text = models.CharField(max_length=300)
    goal_deadline = models.DateTimeField('Deadline')
    def __str__(self):
        return self.goal_text

    def was_published_recently(self):
        return self.goal_deadline >= timezone.now() - datetime.timedelta(days=1)

class Note(models.Model):
    note_text = models.CharField(max_length=300)
    def __str__(self):
        return self.note_text

class Importance(models.Model):
    goal = models.ForeignKey(Goal, on_delete = models.CASCADE)
    importance_text=models.CharField(max_length=10)
    def __str__(self):
        return self.importance_text

daily_planner/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Goal,Importance

class IndexView(generic.ListView):
    template_name = 'daily_planner/index.html'
    context_object_name = 'latest_goals_list'

    def get_queryset(self):
        return Goal.objects.order_by('-goal_deadline')

class DetailView(generic.DetailView):
    model = Goal
    template_name = 'daily_planner/results.html'

    def get_queryset(self):
        return Goal.objects.filter(goal_deadline__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Goal
    template_name = 'daily_planner/results.html'

def vote(request,goal_id):
    goal = get_object_or_404(Goal, pk=goal_id)
    try:
        selected_importance = goal.importance_set.get(pk=request.POST['importance'])
    except (KeyError, Importance.DoesNotExist):
        return render(request, 'daily_planner/detail.html', {
            'goal':goal,
            'error_message': "You didn't did this",
        })
    else:
        selected_importance.save()
        return HttpResponseRedirect(reverse('daily_planner:results', args=(goal.id, )))

daily_planner/templates/daily_planner/detail.html
<h1>{{ goal.goal_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'daily_planner:vote' goal.id %}" method="post">
{% csrf_token %}
{% for goal in goal.importance_set.all %}
    <input type="radio" name="importance" id="importance{{ forloop.counter }}" value="{{ importance.id }}">
    <label for="importance{{ forloop.counter }}">{{ importance.importance_text }}</label><br>
{% endfor %}
<input type="submit" value="vote">
</form>

daily_planner/templates/daily_planner/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'daily_planner/style.css' %}">

{% if latest_goals_list %}
	<ul>
	{% for goal in latest_goals_list %}
		<li><a href="{% url 'daily_planner:detail' goal.id %}">{{goal.goal_text }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>No goals are available</p>
{% endif %}

daily_planner/templates/daily_planner/results.html
<h1>{{ goal.goal_text }}</h1>

<ul>
	{% for importance in goal.importance_set.all %}
	<li>{{ importance.importance_text }} -- { importance.votes }} vote{{ importance.votes|pluralize }}</li>
	{% endfor %}
</ul>

<a href="{% url 'daily_planner:detail' goal.id %}></a>